#!/bin/bash

handle() {
  # if [[ ${1:0:11} == "workspacev2" ]]; then
  #   # workspaceid=${1:13:1}
  #   # eww update currentworkspace="${workspaceid}"
  #   echo $1
  # elif [[ ${1:0:10} == "openwindow" ]]; then
  #   echo $1
  # fi
  case $1 in
  workspacev2*)
    workspaceid=${1:13:1}
    eww-workspace update "${workspaceid}"
    eww-minimize getAppList
    ;;
  activewindowv2*)
    address="0x${1:16}"
    eww update activewindow="${address}"
    ;;
  openwindow*)
    # address="0x${1:12:12}"
    eww-minimize getAppList
    # eww-minimize capture "${address}"
    ;;
  closewindow*)
    eww-minimize getAppList
    ;;
  esac
}

socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
