#!/bin/bash

currentstate=$(eww get touchpad)

if [[ ${currentstate} -eq 1 ]]; then
  hyprctl keyword "device[elan1201:00-04f3:3098-touchpad]:enabled" 0
  eww update touchpad=0
else
  hyprctl keyword "device[elan1201:00-04f3:3098-touchpad]:enabled" 1
  eww update touchpad=1
fi
