#!/bin/bash

operate=$1
address=$2

minimizedshot="/tmp/minimizedshot"

if [[ ${operate} == "close" ]]; then
  eww close preview
elif [[ ${operate} == "open" ]]; then
  if [[ $(eww-minimize isminimize "${address}") == true ]]; then
    exit 0
  fi
  path="${minimizedshot}/${address}.png"
  info=$(hyprctl clients -j | jq ".[] | select(.address==\"${address}\") | .path=\"${path}\"")
  geometry=$(echo "${info}" | jq -r " \"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])\"")
  grim -g "${geometry}" "${path}"
  eww update previewinfo="${info}"
  eww open preview
fi
