local M = {}

M.diagnostics = {
  Error = "󰅙",
  Warn  = "",
  Hint  = "",
  Info  = "󰋼",
  -- Error = "",
  -- Warn  = "",
  -- Hint  = "",
  -- Info  = "",
}

M.dap = {
  DapBreakpoint = { "", "DapError" },
  DapBreakpointCondition = { "󰟃", "DapInfo"},
  DapBreakpointRejected = { "󰃤", "DapError" },
  DapLogPoint = { ".>", "DapLog" },
  DapStopped = { "󰁕", "DapStop" },
}

M.cmp = {
  Array         = "",
  Boolean       = "󰨙",
  Class         = "",
  Codeium       = "󰘦",
  -- Color         = "",
  Color         = "",
  Control       = "",
  Collapsed     = "",
  Constant      = "󰏿",
  Constructor   = "",
  Copilot       = "",
  Enum          = "",
  EnumMember    = "",
  Event         = "",
  Field         = "",
  File          = "",
  Folder        = "",
  Function      = "󰊕",
  Interface     = "",
  Key           = "",
  Keyword       = "",
  Method        = "󰊕",
  Module        = "",
  Namespace     = "󰦮",
  Null          = "",
  Number        = "󰎠",
  Object        = "",
  Operator      = "",
  Package       = "",
  Property      = "",
  Reference     = "",
  -- Snippet       = "",
  Snippet       = '󱄽',
  String        = "",
  -- Struct        = "󰆼",
  Struct        = '󱡠',
  TabNine       = "󰏚",
  Text          = "",
  -- TypeParameter = "",
  TypeParameter = "󰬛",
  -- Unit          = "",
  Unit          = '󰪚',
  Value         = "",
  Variable      = "󰀫",
}

return M
